### ISSUE TITLE
FileNotFoundError in step 3

### ISSUE THREAD

**Issue by drs** [rderelle/Broccoli#19]
Hello, 

I used Broccoli (version 1.3) on a dataset of 160 eukaryotic proteomes. 

```
broccoli.py -steps 1,2,3 -threads 8 -dir Proteomes -path_fasttree /software/apps/core/fasttree/2.1.11/FastTree -phylogenies nj
```

During the `extract para from trees` part of step 3 the analysis crashed with the following error. The analysis of the `example_dataset` from this repository using the same command executed without issues. Do you have any idea what might be causing this issue? 

```
 --- STEP 3: network analysis

 ## parameters
 species overlap  : 0.5
 min edge weight  : 0.1
 min nb hits      : 2
 chimeric edges   : 0.5
 chimeric species : 3
 threads          : 8

 ## get ortho and para
 extract ortho from similarity
 extract ortho from trees
 remove ortho found only once
 extract para from trees
Traceback (most recent call last):
  File "/software/apps/core/broccoli/1.3/broccoli.py", line 153, in <module>
    broccoli_step3.step3_orthology_network(sp_overlap, min_weight, min_nb_hits, chimeric_shared, chimeric_nb_sp, nb_threads)
  File "/software/apps/core/broccoli/1.3/scripts/broccoli_step3.py", line 78, in step3_orthology_network
    extract_para(files_trees)
  File "/software/apps/core/broccoli/1.3/scripts/broccoli_step3.py", line 301, in extract_para
    content_pickle = pickle.load(open(path_tmp_para / filename, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'dir_step3/tmp_para/0_trees.pic'
```

Best, 
Samuel

**Comment by rderelle** [comment]
Hi Samuel, 

I'm afraid I can't see any specific reason associated with this issue. Was there another error message at the end of step 2? Also, are you sure you had enough free disk space?

thanks,
Romain

**Comment by drs** [comment]
Hi Romain,

I don't think there was another error message at the end of step 2. 

Disk space might be the issue, I probably had 2-3 TB of free disk space. Should this the enough for `dir_step3/tmp_para/0_trees.pic` ? 


Thanks, 
Samuel

**Comment by JBerthelier** [comment]
Hello, 
I also have the exact same error, with a dataset of 120 proteome composed of about 40,000 aa sequences each. 
Did you figure out the probleme? I have no space limitation, using 20 cpu and 400 go Ram.
Best regards

python3 broccoli.py -dir proteomes/ -threads 20 -path_fasttree path/fasttree-2.1.11/FastTree

**Comment by rderelle** [comment]
The pipeline is running smoothly on my server. If someone could share a dataset and any additional details (e.g., software versions), I'd be happy to run it on my end and debug it. Thanks.
