### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by fmarletaz** [rderelle/Broccoli#8]
Hi, 
Broccoli crashed at tep2 with the following error. I don't get what the problem could be.  Thanks! 

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/flash/RokhsarU/ferdi/miniconda3/envs/py37/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/flash/RokhsarU/ferdi/miniconda3/envs/py37/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/flash/RokhsarU/ferdi/Genomes/Urchins/broccoli/Broccoli-1.2/scripts/broccoli_step2.py", line 402, in process_file
    prot = all_ref_prot[c]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./Broccoli-1.2/broccoli.py", line 148, in <module>
    broccoli_step2.step2_phylomes(evalue, max_per_species, path_diamond, path_fasttree, trim_thres, phylo_method, nb_threads)
  File "/flash/RokhsarU/ferdi/Genomes/Urchins/broccoli/Broccoli-1.2/scripts/broccoli_step2.py", line 78, in step2_phylomes
    multithread_process_file(list_files, nb_threads)
  File "/flash/RokhsarU/ferdi/Genomes/Urchins/broccoli/Broccoli-1.2/scripts/broccoli_step2.py", line 151, in multithread_process_file
    results_2 = tmp_res.get()
  File "/flash/RokhsarU/ferdi/miniconda3/envs/py37/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
IndexError: list index out of range
```

**Comment by rderelle** [comment]
Hi,

my guess is that FastTree has generated some error messages that I'm not aware of, leading Broccoli to overestimate the number of phylogenetic trees.
I would need to run the FastTree analyses myself and have a look at the output. Would you have a way to share with me the alignment file ? It's probably the last that has been generated. For instance if index '8': the file 'step2/8/alis_8.phy'.

Romain

**Comment by rderelle** [comment]
if not possible, please try with FastTree 2.1.10. It should work fine.

I just saw that some warning messages have been added to the last version of FastTree (2.1.11). These could be the source of this issue if you have used that version.

**Comment by fmarletaz** [comment]
Thanks a lot Romain for your prompt reply. I don't mind at all sharing the alignment: https://www.dropbox.com/s/lu40m1i291k1ilq/alis_15.phy.gz?dl=0
I am retrying with FastTree 2.1.10, I will let you know!  

Ferdi

**Comment by fmarletaz** [comment]
I just tried with  FastTree 2.1.10 and reached the same error.

**Comment by rderelle** [comment]
I found the problem: one of your alignments generates the warning "WARNING! 100.0% NUCLEOTIDE CHARACTERS -- IS THIS REALLY A PROTEIN ALIGNMENT?"

I have modified the script of step2 to ignore this warning message (tiny modification at line 384).
Unfortunately I would need the full dataset to test it. Could you please give it a try with the new file scripts/broccoli_step2.py and let me know ?

thanks
Romain

**Comment by fmarletaz** [comment]
Hello! I tried and it worked, thanks for the fix!
